### ISSUE TITLE
Error 500 on start-result service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#1201]
Today we got a 500 on the start-result service:
```
unexpected error: record not found, stack trace: goroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/France-ioi/AlgoreaBackend/v2/app/service.AppHandler.ServeHTTP.func1()\n\t/home/circleci/project/app/service/handler.go:34 +0x1ff\npanic({0xca4360, 0xc00015f9a0})\n\t/usr/local/go/src/runtime/panic.go:884 +0x213\ngithub.com/France-ioi/AlgoreaBackend/v2/app/database.(*DB).inTransactionWithCount.func1()\n\t/home/circleci/project/app/database/db.go:134 +0x219\npanic({0xca4360, 0xc00015f9a0})\n\t/usr/local/go/src/runtime/panic.go:884 +0x213\ngithub.com/France-ioi/AlgoreaBackend/v2/app/service.MustNotBeError(...)\n\t/home/circleci/project/app/service/errors.go:95\ngithub.com/France-ioi/AlgoreaBackend/v2/app/api/items.(*Service).startResult.func1(0xc000396c00)\n\t/home/circleci/project/app/api/items/start_result.go:128 +0x6a9\ngithub.com/France-ioi/AlgoreaBackend/v2/app/database.(*DataStore).InTransaction.func1(0xd2a8c0?)\n\t/home/circleci/project/app/database/data_store.go:226 +0x38\ngithub.com/France-ioi/AlgoreaBackend/v2/app/database.(*DB).inTransactionWithCount(0xc000289170, 0xc0004529d8, 0x0, {0x0?, 0x0, 0x0})\n\t/home/circleci/project/app/database/db.go:148 +0x24a\ngithub.com/France-ioi/AlgoreaBackend/v2/app/database.(*DB).inTransaction(...)\n\t/home/circleci/project/app/database/db.go:99\ngithub.com/France-ioi/AlgoreaBackend/v2/app/database.(*DataStore).InTransaction(0xc000452ab0, 0xc000452ac8, {0x0, 0x0, 0x0})\n\t/home/circleci/project/app/database/data_store.go:224 +0x105\ngithub.com/France-ioi/AlgoreaBackend/v2/app/api/items.(*Service).startResult(0xc0000a8120, {0x7f63bef62510, 0xc0002053c0}, 0xc0001fd000)\n\t/home/circleci/project/app/api/items/start_result.go:93 +0x385\ngithub.com/France-ioi/AlgoreaBackend/v2/app/service.AppHandler.ServeHTTP(0x100?, {0x7f63bef62510?, 0xc0002053c0?}, 0x0?)\n\t/home/circleci/project/app/service/handler.go:41 +0xc3\nnet/http.HandlerFunc.ServeHTTP(0xf2bea0?, {0x7f63bef62510?, 0xc0002053c0?}, 0xf22250?)\n\t/usr/local/go/src/net/http/server.go:2122 +0x2f\ngithub.com/France-ioi/AlgoreaBackend/v2/app/service.ParticipantMiddleware.func1.1({0x7f63bef62510, 0xc0002053c0}, 0xc0001fcf00)\n\t/home/circleci/project/app/service/participant.go:39 +0x27c\nnet/http.HandlerFunc.ServeHTTP(0xf274c0?, {0x7f63bef62510?, 0xc0002053c0?}, 0xc0002053c0?)\n\t/usr/local/go/src/net/http/server.go:2122 +0x2f\ngithub.com/France-ioi/AlgoreaBackend/v2/app/auth.UserMiddleware.func1.1({0x7f63bef62510?, 0xc0002053c0}, 0xc0001fce00)\n\t/home/circleci/project/app/auth/middleware.go:47 +0x16b\nnet/http.HandlerFunc.ServeHTTP(0xf2bea0?, {0x7f63bef62510?, 0xc0002053c0?}, 0x1477800?)\n\
```

**Comment by smadbe** [comment]
Got 11x the same crash on 22-23/10.

**Comment by zenovich** [comment]
When there are two concurrent requests to resultStart with same parameters, one of them doesn't really create/update the result as it's been started by another request. So, the result is considered to be unchanged and the SELECT query doesn't see it in REPEATABLE READ isolation level. There is a MySQL bug describing this behaviour: https://bugs.mysql.com/bug.php?id=116067
